'use client';
import { useEffect, useMemo, useState } from 'react';
import { sentenceSegments } from '@/lib/fieldproof/transcription';
import { tagWords, type WordModel } from '@/lib/fieldproof/word-language';
import { acceptSpellingSuggestion, teluguSplitSuggestions, type TeluguLexicon } from '@/lib/fieldproof/spelling-suggestions';
import type { SpeechLanguage } from '@/lib/fieldproof/transcription';
import s from './transcriber.module.css';
const names = {en:'English',hi:'Hindi',te:'Telugu',bn:'Bengali',mr:'Marathi',ta:'Tamil',zh:'Mandarin',es:'Spanish',ar:'Arabic',fr:'French',uncertain:'Uncertain',other:'Other'};
export function TranscriptView({text,onChange,disabled,language}:{text:string;onChange:(text:string)=>void;disabled:boolean;language:SpeechLanguage}) {
  const [view,setView] = useState<'edit'|'words'|'sentences'>('edit'); const [lexicon,setLexicon] = useState<TeluguLexicon|null>(null); const [model,setModel] = useState<WordModel|null>(null); const [modelError,setModelError] = useState(false);
  useEffect(()=>{ const controller = new AbortController(); void fetch('/models/word-language.json',{signal:controller.signal}).then(response=>{if(!response.ok) throw new Error('Model unavailable');return response.json();}).then(setModel).catch(cause=>{if(cause.name !== 'AbortError')setModelError(true);}); return()=>controller.abort();},[]);
  useEffect(()=>{const controller=new AbortController();void fetch('/models/telugu-romanized-lexicon.json',{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error('Lexicon unavailable');return response.json();}).then(setLexicon).catch(()=>{});return()=>controller.abort();},[]);
  const suggestions=useMemo(()=>teluguSplitSuggestions(text,language,lexicon,model),[text,language,lexicon,model]);
  const tokens = useMemo(()=>tagWords(text,model,language),[text,model,language]); const sentences = useMemo(()=>sentenceSegments(text),[text]);
  const counts = tokens.filter(token=>token.word).length;
  return <section className={s.transcript} aria-label="Original-language transcript"><div className={s.transcriptTop}><h2>Original spoken words · editable</h2><div className={s.segmented} aria-label="Transcript view">{(['edit','words','sentences'] as const).map(value=><button key={value} aria-pressed={view===value} onClick={()=>setView(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div>
    {view==='edit' ? <><label htmlFor="transcript-text" className={s.srOnly}>Edit transcript</label><textarea id="transcript-text" value={text} onChange={event=>onChange(event.target.value)} disabled={disabled} maxLength={10000} placeholder="Your words appear here. Speak Hindi, Telugu, English, or a mix. You can also type directly." spellCheck={false}/></> : view==='words' ? <><div className={s.legend}>{(['en','hi','te','bn','mr','ta','zh','es','ar','fr','uncertain'] as const).map(language=><span key={language} data-language={language}>{names[language]}</span>)}</div><div className={s.wordMap}>{tokens.map(token=>token.word ? <span key={token.start} data-language={token.language} title={`${names[token.language]} · ${token.source}`}><span>{token.text}</span><small>{names[token.language]}</small></span> : <span className={s.punctuation} key={token.start}>{token.text}</span>)}</div><p className={s.help}>{modelError ? 'Learned word model unavailable; showing script and small-vocabulary hints.' : 'Word-language hints combine a locally trained character model, scripts and common vocabulary.'} Shared spellings remain uncertain. Hindi and Marathi share Devanagari, so choose the spoken language to label that script. Latin words in Spanish or French may also need review. These hints are not speech confidence.</p></> : <div className={s.sentences}>{sentences.length ? sentences.map((sentence,index)=><p key={index}><small>{String(index+1).padStart(2,'0')}</small>{sentence}</p>) : <p>Sentences appear here after you speak or type.</p>}<p className={s.help}>Sentence boundaries follow punctuation and language-aware segmentation. Missing punctuation can still join sentences.</p></div>}
    {suggestions.length>0 && <div className={s.spellingSuggestions} aria-label="Possible Telugu spellings"><strong>Check these Telugu words against the audio</strong>{suggestions.map(item=><div key={item.start}><span><b>{item.heard}</b> → <b>{item.replacement}</b> <small>({item.native})</small></span><button disabled={disabled} onClick={()=>onChange(acceptSpellingSuggestion(text,item))}>Use {item.replacement}</button></div>)}<p>Suggestions come from a local spelling dictionary. Your original machine transcript remains available.</p></div>}
    <div className={s.transcriptMeta}><span>{counts} words · {sentences.length} {sentences.length===1?'sentence':'sentences'}</span><span>{text.length.toLocaleString()} / 10,000 characters</span></div>
  </section>;
}
